FROM docker-virtual.artefact-repo.pole-emploi.intra/openjdk:8-jdk

RUN wget -O /usr/lib/provenclient-rest-1.6.0-131-all.jar "http://artefact-repo.pole-emploi.intra/artifactory/Prod/fr/pe/pkg/provenclient/provenclient-rest/1.6.0-131/provenclient-rest-1.6.0-131-all.jar"
